# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

dist: trusty

php:
  # Silverstripe 3.x
  # NOTE: Travis-CI is only supporting PHP 5.4+ from late 2017.
  - 5.4
  # Silverstripe 4
  - 5.5

env:
  matrix:
    #
    # Silverstripe 3.x
    #
    - DB=MYSQL CORE_RELEASE=3.1
    # Silverstripe 4
    #
    - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    #
    # Silverstripe 3.x
    #
    - php: 5.4
      env:
        - DB=MYSQL
        - CORE_RELEASE=3.1
    - php: 5.4
      env:
        - DB=PGSQL
        - CORE_RELEASE=3.2
    - php: 5.5
      env:
        - DB=MYSQL
        - CORE_RELEASE=3.3
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
        - CORE_RELEASE=3
    #
    # Silverstripe 4
    #
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
    - php: 7.0
      env:
        - DB=PGSQL
    - php: 7.1
      env:
        - DB=MYSQL
        - PDO=1

before_script:
  #
  # Silverstripe 3
  #
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

  #
  # Silverstripe 4
  #
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:1.0.x-dev
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.0.x-dev; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  #
  # Silverstripe 3
  #
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs YOUR_MODULE_NAME/src/ YOUR_MODULE_NAME/tests/ -n; fi
  - vendor/bin/phpunit YOUR_MODULE_NAME/tests/
  #
  # Silverstripe 4
  #
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=vendor/silverstripe/framework/phpcs.xml.dist src/ tests/ ; fi
